### ISSUE TITLE
Error on attempting to run Example application 

### ISSUE THREAD

**Issue by qbunt** [unindented/electron-installer-windows#121]
**What version of `electron-installer-windows` are you using?**
v0.2.0

**What version of `node` and `npm` are you using?**
node - v6.9.1
npm - 3.10.8

**What operating system are you using?**
OS X 10.11.6

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
No

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```
(previous step missing an 'npm install')
Scrollback to the output is here
https://gist.github.com/qbunt/4eebd98d63c1ba042bae8451c2860cfd

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
The above steps

**What did you expect to happen?**
A completed .exe build of the example app.

**What actually happened?**
The above error.

**Comment by qbunt** [comment]
I should also add that this was on a fresh install of mono and wine via homebrew. Any hints here would be great, I thought the error was something caused by my application, I realize it's a very hard issue to resolve.

**Comment by unindented** [comment]
It sounds like an issue with Squirrel and Mono. Here's a similar report: https://github.com/electron/windows-installer/issues/63

I'm afraid I don't know that much about Squirrel's internals, so I'd suggest building on a Windows box...

**Comment by qbunt** [comment]
For what it's worth, this is not the only project I'm unable to build with, it's been basically every project I've tried for generating exe or msi installers that fails in a similar (though not identical way). Thanks for the fast response man, feel free to close if you're confident it's something upstream out of your control. Cheers!

**Comment by qbunt** [comment]
@unindented maybe it should note in your readme that this doesn't currently run on a Mac, it would have saved me a bunch of time.
