### ISSUE TITLE
Failing to build my app (W10), is there any specific requirement I am missing?

### ISSUE THREAD

**Issue by KYSSelectron** [unindented/electron-installer-windows#127]
Is there any specific structure for the packaged app that is necessary to work? I have

```
/app-win32-x64/locales/*
/app-win32-x64/resources/
/app-win32-x64/resources/app.asar
/app-win32-x64/resources/electron.asar
/app-win32-x64/resources/node_modules/*
/app-win32-x64/app.exe
/app-win32-x64/*
```

And my package.json, from which I execute npm run make

```
{
  "name": "app",
  "license": "GPL",
  "productName": "app",
  "version": "1.0.0",
  "author": "...",
  "description": "...",
  "devDependencies": {
    "asar": "^0.12.3",
    "electron-installer-windows": "^0.2.0",
    "electron-packager": "^8.3.0",
    "electron-prebuilt": "^1.4.8",
    "gulp": "^3.9.1",
    "gulp-bower": "0.0.13",
    "rcedit": "^0.7.0"
  },
  "dependencies": {
    "highcharts": "^5.0.5",
    "jquery": "^3.1.1",
    "remote": "^0.2.6"
  },
  "scripts": {
    "start": "electron .",
    "package": "electron-packager ./app Kyss_electron --platform=win32 --arch=x64  --asar=true",
    "make": "electron-installer-windows --src app-win32-x64/ --dest dist/"
  }
}
```

But it fails, without saying any specific but that the problem is probably in my app. So what can be wrong with my app?

Thanks,

**What version of `electron-installer-windows` are you using?**
0.2.0

**What version of `node` and `npm` are you using?**
3.10.9

**What operating system are you using?**
Windows 10

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
Not tried

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
Trying to pack my app

**What did you expect to happen?**
To build a single .exe file

**What actually happened?**
It gives the error "Error: Error creating package: Error executing file (1):"
...
"The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has incomplete content. List of possible elements expected: 'description' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'."

**Comment by unindented** [comment]
The error says `List of possible elements expected: 'description' in namespace`, so why not try adding a `description`field to your `package.json`, or passing it as a config parameter to `electron-windows-installer`?

**Comment by kyssproject** [comment]
But you can see in the package.json that there already is a description element.

**Comment by unindented** [comment]
Try building the example app and compare it with yours. That's usually the easiest way to identify the problem.

**Comment by rwittenburg** [comment]
I had this issue as well, I had to do a few things to fix it:

1. Following https://docs.npmjs.com/files/package.json make sure you have the "author" field set properly... specifically the url field:
  "author": {
	  "name": "My Name",
	  "email": "my@emailaddress.com",
	  "url": "https://www.mywebsite.com"
  },

2. In your config .json (or command line args) set the icon field AND the iconUrl field (which has to point to a ico on http or https url)

Remember that you have to repackage each time you try to run setup (you can't just update the .json config and run setup).

This solved my issue so hopefully it helps someone else in the future.

**Comment by geek4teck** [comment]
I got the same issue yesterday and I fixed it this way:

Added a new file config.json

{
  "authors":["Author Name"],
  "description":"Description goes here",
  "productDescription":"ProductDescription goes here"
}

and while calling     "make": "electron-installer-windows --src app-win32-x64/ --dest dist/"

add another parameter --config

    "make": "electron-installer-windows --src app-win32-x64/ --dest dist/ --config config.json"

Check the correct path for config.json

This problem should get solved.

Thanks

**Comment by unindented** [comment]
Cool, thanks for the help!
