### ISSUE TITLE
Relation to windows-installer

### ISSUE THREAD

**Issue by havenchyk** [unindented/electron-installer-windows#14]
Hi, thanks for all you work on this package, but why have you created it? 

There is a ready to use https://github.com/electronjs/windows-installer, why not just to contribute to the windows installer instead? 

Could you please clarify it?

**Comment by havenchyk** [comment]
Btw, please, take a look at https://github.com/loopline-systems/electron-builder as well, it's a complex solution for windows and osx as well.

**Comment by unindented** [comment]
@havenchyk CoffeeScript pushed me away from contributing to that codebase. I see it has been turned into JavaScript recently.

I'll take a look. Thanks for the heads up.

**Comment by havenchyk** [comment]
@unindented yep, it's might be better to have a single solution. Feel free to add anything to windows-installer.
