### ISSUE TITLE
Error package windows

### ISSUE THREAD

**Issue by azisunmul** [unindented/electron-installer-windows#15]
[npm-debug.txt](https://github.com/unindented/electron-installer-windows/files/175115/npm-debug.txt)

**Comment by austinmayer** [comment]
+1

Same errors when packaging for windows.

**Comment by unindented** [comment]
@azisunmul @austinmayer, just tried building the example app on OSX with Node 4.4.3 and things work fine, and Travis CI builds are green, so this suggests an environment problem.

Can you clone this repository, `cd` into the `example` directory, and run the following?

```
$ DEBUG='electron-installer-windows' npm run build
```

Can you also try using either the latest LTS version of Node (4.4.3) or the latest stable version (5.11.0) and report back? What operating system are you using to build the app?

**Comment by unindented** [comment]
Closing for now. Please reopen if you manage to provide the requested information.
