### ISSUE TITLE
electron-installer-windows expect electron.exe

### ISSUE THREAD

**Issue by nicolasandrieux** [unindented/electron-installer-windows#179]
electron-installer-windows verion 0.2.0
node version 6.9.4
npm version 3.10.10
windows 10

I'm building an installer using the command line without using config file and doing that the installer expect a file named electron.exe even if I pass name in params

```
electron-installer-windows --src bin/Myappname-win32-x64/ --dest bin/installers/ --name "Myappname" --icon resources/mast.ico --options.version 0.0.20 --options.name "Myappname" --options.product-name "Myappname" --options.icon-url resources/myappico.ico --options.setup-icon resources/myappico.ico --options.skip-update-icon true --options.remote-releases "http://myappdomain.com:48821/update/win32_x64/0.0.20"
```

If I rename the exe file by electron.exe it's working, but then the name of the is become electron :(

I not using a config file because name and version are parameters set to the console

**Comment by nicolasandrieux** [comment]
Actually I just try using a json file with config inside and this is the same, the builder keep looking for electron.exe :(

**Comment by nicolasandrieux** [comment]
ok so I don't know if this is expected but here it's what is happening:

the function getDefault is building the exe name using the name set in package.json only (and default is electron.exe), 
then the script is using the property passed in the config file but it never rewrite the exe name, so the name have to be set on the package.json from the src folder.

my issue with that is the name of the app is a bit dynamics because we have a dev a staging and a prod version.

**Comment by unindented** [comment]
You don't have to rename `electron.exe`. You should be using a tool like `electron-packager`, which renames the app based on your `productName` or `name` fields. So the correct fix in your case is to provide the right info in your `package.json` file, so that `electron-packager` does the right thing.

**Comment by unindented** [comment]
When in doubt, look at the example app: https://github.com/unindented/electron-installer-windows/tree/master/example
