### ISSUE TITLE
Not able to generate windows exe on mac machine

### ISSUE THREAD

**Issue by sujit11oct** [unindented/electron-installer-windows#220]
i am using "electron-installer-windows": "^0.2.0",

node --version
v6.9.4
npm --version
3.10.10

 Is it possible to generate both dmg and exe installers from jenkins running in mac machine. We also want the code signing for the mac app. 
i have mono ,wine and squirrell set up but still i am facing the issue.

steps 1). i am running electron-packager  to generate windows 64 bit specific files.
step 2) Running electron-installer-packager to generate exe,nupkg and RELEASES file
i am getting error in second step.
+ electron-installer-windows --src=dist/win/CloudConnectUtility-win32-x64/ --dest=dist/win/installers/ --iconUrl=/apps/CCUWindowsIcon/icon.ico --homepage=https://www.npmjs.com/package/electron-installer-windows config.js
Creating package (this may take a while)
Error: Error releasifying package: Error executing file (255): 
mono /usr/local/lib/node_modules/electron-installer-windows/vendor/squirrel/Squirrel-Mono.exe --releasify 
System.InvalidOperationException: The input package file /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/electron-1171112-8155-1dz2654.vzvyy3z0k9/CloudConnectUtility_1.0.0/squirrel/CloudConnectUtility.1.0.0.nupkg targets no platform and cannot be transformed into a release package.
at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2[T,TResult] releaseNotesProcessor, System.Action`1[T] contentsPostProcessHook) [0x000ad] in <a738fa86ffa346549b0ac27411465911>:0
at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, System.Boolean generateMsi) [0x00208] in <a738fa86ffa346549b0ac27411465911>:0
at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00439] in <a738fa86ffa346549b0ac27411465911>:0
at Squirrel.Update.Program.main (System.String[] args) [0x00082] in <a738fa86ffa346549b0ac27411465911>:0
at Squirrel.Update.Program.Main (System.String[] args) [0x00006] in <a738fa86ffa346549b0ac27411465911>:0

i have following  configuration:

electron-packager . 'CloudConnectUtility' --overwrite --platform win32 --arch x64 --asar  --out dist/win --prune true --icon build/icon.ico  

electron-installer-windows  --src=dist/win/CloudConnectUtility-win32-x64/ --dest=dist/win/installers/ --iconUrl=https://s3/path/to/apps/CCUWindowsIcon/icon.ico --homepage=https://www.npmjs.com/package/electron-installer-windows

package.json:
  {
  "name": "CloudConnectUtility",
  "productName": "Cloud Connect Utility",
  "author": "sujit",
  "description": "Cloud Connect Utility",
  "main": "tfcc-electron.js",
  "version": "1.0.0",
  "appDirectory": "/tmp/build/my-app-64",
  "outputDirectory": "/tmp/build/installer64",
  "devDependencies": {
    "autoprefixer-core": "^5.2.1",
    "aws-sdk": "^2.6.5",
    "electron-builder": "^7.14.1",
    "electron-installer-windows": "^0.2.0",
    "electron-packager": "^7.6.0",
    "electron-prebuilt": "^1.3.4",
    "electron-rebuild": "^1.2.0",
    "grunt": "^0.4.5",
    "grunt-angular-templates": "^0.5.7",
    "grunt-cli": "^1.2.0",
    "grunt-concurrent": "^1.0.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-compress": "^1.3.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-connect": "^0.9.0",
    "grunt-contrib-copy": "^0.7.0",
    "grunt-contrib-cssmin": "^0.12.0",
    "grunt-contrib-htmlmin": "^0.4.0",
    "grunt-contrib-imagemin": "^1.0.0",
    "grunt-contrib-jshint": "^0.11.0",
    "grunt-contrib-uglify": "^0.7.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-electron-packager": "0.0.8",
    "grunt-filerev": "^2.1.2",
    "grunt-google-cdn": "^0.4.3",
    "grunt-jscs": "^1.8.0",
    "grunt-karma": "^2.0.0",
    "grunt-maven-deploy": "^0.2.1",
    "grunt-newer": "^1.1.0",
    "grunt-ng-annotate": "^0.9.2",
    "grunt-postcss": "^0.5.5",
    "grunt-svgmin": "^2.0.0",
    "grunt-svn-bump": "^0.2.1",
    "grunt-svn-tag": "^0.5.1",
    "grunt-usemin": "^3.0.0",
    "grunt-wiredep": "^2.0.0",
    "jasmine-core": "^2.4.1",
    "jit-grunt": "^0.9.1",
    "jshint-stylish": "^1.0.0",
    "karma": "^1.1.2",
    "karma-electron-launcher": "^0.1.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.1",
    "load-grunt-tasks": "^3.5.0",
    "phantomjs-prebuilt": "^2.1.9",
    "sqlite3": "^3.1.4",
    "time-grunt": "^1.0.0",
    "username": "^2.2.2"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "test": "karma start test/karma.conf.js",
    "start": "electron .",
    "windows-app": "electron-packager . 'CloudConnectUtility' --overwrite --platform win32 --arch x64 --asar  --out dist/win --prune true --icon build/icon.ico  --win32metadata.CompanyName=\"Cloud Connect Utility\" --win32metadata.ProductName=\"Cloud Connect Utility\" --win32metadata.FileDescription=\"Cloud Connect Utility\" ",
    "windows-exe": "electron-installer-windows  --src 'dist/win/CloudConnectUtility-win32-x64/' --dest 'dist/win/installers/' --iconUrl=https://s3/path/to/apps/CCUWindowsIcon/icon.ico --homepage=https://www.npmjs.com/package/electron-installer-windows ",
    "dist": "build --x64"
  },
  "dependencies": {
    "aws-sdk": "^2.6.5",
    "electron-squirrel-startup": "^1.0.0",
    "sqlite3": "^3.1.4",
    "node-dir": "^0.1.16",
    "bluebird": "^3.4.6",
    "chokidar": "^1.6.0",
    "electron-log": "^2.2.6",
    "q": "^1.4.1",
    "temp": "^0.8.3",
    "s3-upload-stream": "^1.0.7",
    "winston": "^2.3.1",
    "winston-daily-rotate-file": "^1.4.6"
  },
  "build": {
    "appId": "tfc.tigers.ccu",
    "app-category-type": "utilities",
    "files": [
      "**/*",
      "dist/*",
      "build/*"
    ],
    "win": {
      "iconUrl": "s3://path/to/icon.ico"
    }
  }
}
Config.json
{
  "iconUrl": "/apps/CCUWindowsIcon/icon.ico",
  "tags": [
     "Utility"
    ],
  "name": "Cloud Connect Utility",
  "productName": "Cloud Connect Utility",
  "description": "Cloud Connect Utility",
  "productDescription": "Cloud Connect Utility",
  "copyright": "Copyright © 2017 sujit,
  "authors": [
       "sujit"
   ],
  "owners": [
       "sujit"
   ],
  "homepage":"https://www.npmjs.com/package/electron-installer-windows",
  "exe": "Cloud Connect Utility.exe",
  "requireLicenseAcceptance": false,
  "noMsi": false
  }
  
Any suggestion or solution is welcome.

**Comment by fcastilloec** [comment]
This should be fixed with the latest release. I'll reopen the issue if something new comes up
