### ISSUE TITLE
Error creating package with NuGet

### ISSUE THREAD

**Issue by palbcn** [unindented/electron-installer-windows#228]
**What version of `electron-installer-windows` are you using?**
1.0.2

**What version of `node` and `npm` are you using?**
v8.9.4
v5.8.0

**What operating system are you using?**
Windows 7 Professional
Service Pack 1

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**

I can reproduce the error with the sample electron app
```
> git clone https://github.com/electron/electron-quick-start
> cd electron-quick-start
> npm install
> electron-packager . --out dist
> electron-installer-windows --src dist/electron-quick-start-win32-x64/ --dest dist/installer/
```

**What did you expect to happen?**
succesfully build the installer

**What actually happened?**

> Error: Error creating package with NuGet: Error executing command (Exited with status 1):
> C:\Users\Pppp\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack c:\temp\electron-86521BJCLm8LWRXn\electron-quick-start_1.0.0\nuget\electron-quick-start.nuspec -BasePath c:\temp\electron-86521BJCLm8LWRXn\electron-quick-start_1.0.0\electron-quick-start -OutputDirectory c:\temp\electron-86521BJCLm8LWRXn\electron-quick-start_1.0.0\nuget -NoDefaultExcludes
> URI no v�lido: no se puede determinar el formato del URI.

the complete debug log is
[electron-installer-windows-error-log.txt](https://github.com/unindented/electron-installer-windows/files/1907060/electron-installer-windows-error-log.txt)

**Comment by fcastilloec** [comment]
Hi, thanks for reporting this. I'll try to fix this in a new release.
As a workaround, always make sure that your `package.json` field is an object containing a `url`, or if it's a string, make sure it has a url wrapped around parenthesis.
You can read about how it should be done here: https://docs.npmjs.com/files/package.json#people-fields-author-contributors

**Comment by fcastilloec** [comment]
This has been fixed in the latest release. Try updating to `v1.1.0` and let me know how it goes

**Comment by VishalChauha** [comment]
here is my package.json file

> {
>   "name": "muon-quick",
>   "version": "1.0.0",
>   "description": "A minimal Muon application",
>   "main": "main.js",
>   "scripts": {
>     "start": "node setup.js"
>   },
>   "repository": "https://github.com/brave/muon-quick",
>   "keywords": [
>     "Muon",
>     "quick",
>     "start",
>     "tutorial",
>     "demo"
>   ],
>   "author": "Brave Software",
>   "license": "CC0-1.0",
>   "devDependencies": {
>     "electron": "^1.7.6",
>     "electron-builder": "^19.27.7",
>     "electron-prebuilt": "brave/electron-prebuilt"
>   }
> }
> 

and
i got error why try to run create exe from package

`Error: Error creating package with NuGet: Error executing command (Exited with status 1):
C:\Users\Admin\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\Admin\AppData\Local\Temp\electron-4868eS3jYL4dmhFv\muon-quick_1.0.0\nuget\muon-quick.nuspec -BasePath C:\Users\Admin\AppData\Local\Temp\electron-4868eS3jYL4dmhFv\muon-quick_1.0.0\muon-quick -OutputDirectory C:\Users\Admin\AppData\Local\Temp\electron-4868eS3jYL4dmhFv\muon-quick_1.0.0\nuget -NoDefaultExcludes
File not found: 'muon-quick.exe'.`

how can i fix this?

**Comment by ksummersill2** [comment]
> OutputDirectory

You could probably go to the node_modules -> electron-windows-installer -> install.js file and modify the path to the muon-quick.exe. Just look for OutputDirectory in the installer.js file.

**Comment by ksummersill2** [comment]
I am currently getting the following error:
Creating package (this may take a while)
Error: Error creating package with NuGet: Error executing command (Exited with status 1):
C:\Users\ksummersill\AppData\Roaming\npm\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\temp\electron-24488XbZ8Hxz7chub\eodims_0.0.1\nuget\eodims.nuspec -BasePath C:\temp\electron-24488XbZ8Hxz7chub\eodims_0.0.1\eodims -OutputDirectory C:\temp\electron-24488XbZ8Hxz7chub\eodims_0.0.1\nuget -NoDefaultExcludes
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

    at err (C:\Users\ksummersill\AppData\Roaming\npm\node_modules\electron-installer-windows\src\installer.js:31:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) 'Error: Error creating package with NuGet: Error executing command (Exited with status 1):\nC:\\Users\\ksummersill\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\temp\\electron-24488XbZ8Hxz7chub\\eodims_0.0.1\\nuget\\eodims.nuspec -BasePath C:\\temp\\electron-24488XbZ8Hxz7chub\\eodims_0.0.1\\eodims -OutputDirectory C:\\temp\\electron-24488XbZ8Hxz7chub\\eodims_0.0.1\\nuget -NoDefaultExcludes\nThe specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.\r\n\n    at err (C:\\Users\\ksummersill\\AppData\\Roaming\\npm\\node_modules\\electron-installer-windows\\src\\installer.js:31:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)'

**Comment by fcastilloec** [comment]
This bug has been closed for a while. The originally reported error has been fixed. If you believe that you found a bug in our code, please open a new issue. If you're asking for help on how to use the module, and why it's not working for you, Github issues is not the place for that.
