### ISSUE TITLE
Continuous Integration - Docker Image

### ISSUE THREAD

**Issue by moroine** [unindented/electron-installer-windows#233]
Hello,

I am trying to create the installer using continuous integration. 

I manage to make it working on my Ubuntu but I didn't found yet a proper docker image to use in CircleCi.

Do you have any recommendation?

**Comment by fcastilloec** [comment]
Sorry, but I don't use CircleCI so can't help you there. I thought they had a running Linux virtual machine that you could use to build. I personally use Travis to build in general, but I mainly use AppVeyor to build anything related to Windows since I can also run tests specific to Windows in AppVeyor

**Comment by moroine** [comment]
I will just let a feedback here, at least to let people who are looking to achieve this to know what would be the issues.

- Using docker image [electronuserland/builder:wine-mono](https://hub.docker.com/r/electronuserland/) not working with following error `System.MissingMethodException: Method 'Array.Empty' not found.`. The issue is that mono version is v4.x.x but Nuget works on v5.x.x [see](https://github.com/NuGet/Home/issues/6790)
- Extending [electronuserland/builder:wine](https://hub.docker.com/r/electronuserland/) and [installing mono v5.x.x](https://www.mono-project.com/download/stable/#download-lin) will endup with the following error `wine: Bad EXE format for Z:\root\repo\node_modules\electron-installer-windows\vendor\squirrel\7z.exe.` which is due to 7zip shipped in electron-installer-windows is in 64bits. You can replace it with the 32bits version, to make it working like explained [here](https://github.com/electron/windows-installer/issues/186#issuecomment-313222658) but I'm not fan of that solution.


So Iv'e ended-up doing this myself, you can find a working docker [here](https://hub.docker.com/r/adactive/docker-electron-installer-windows/)
