### ISSUE TITLE
Example Fail

### ISSUE THREAD

**Issue by miso293** [unindented/electron-installer-windows#27]
Hi,

when I Start 
 
npm run build

on the example i got following Error:

Creating package (this may take a while)
[Error: Error creating package: Error executing file (1):
C:\Beispiel\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\micha\AppData\Local\Temp\electron-116415-2684-1k9hxcy\poopie_0.0.1\nuget\poopie.nuspec -BasePath C:\Users\micha\AppData\Local\Temp\electron-116415-2684-1k9hxcy\poopie_0.0.1\poopie -OutputDirectory C:\Users\micha\AppData\Local\Temp\electron-116415-2684-1k9hxcy\poopie_0.0.1\nuget -NoDefaultExcludes
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
] 'Error: Error creating package: Error executing file (1): \nC:\\Beispiel\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\micha\\AppData\\Local\\Temp\\electron-116415-2684-1k9hxcy\\poopie_0.0.1\\nuget\\poopie.nuspec -BasePath C:\\Users\\micha\\AppData\\Local\\Temp\\electron-116415-2684-1k9hxcy\\poopie_0.0.1\\poopie -OutputDirectory C:\\Users\\micha\\AppData\\Local\\Temp\\electron-116415-2684-1k9hxcy\\poopie_0.0.1\\nuget -NoDefaultExcludes\nThe specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.\r\n\n    at C:\\Beispiel\\node_modules\\electron-installer-windows\\src\\installer.js:273:21\n    at ChildProcess.<anonymous> (C:\\Beispiel\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:92:20)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:827:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)'

Can you help me ?

Thanks from Germany

**Comment by unindented** [comment]
The error message seems pretty clear: one of your paths is too long. Can you paste the full path to your app?

In any case, my suggestions would be:

1. Move your app to a shorter path, e.g. `C:\Users\micha\app`.
2. Use Node 5 or 6, as those versions use npm 3, which flattens your dependency folder, resulting in shorter paths.

**Comment by miso293** [comment]
Hi,

 

with a new Node Version 6 it Works :)

 

Thank you very much

 

Have a nice Week

 

Michael

 

Von: Daniel Perez Alvarez [mailto:notifications@github.com] 
Gesendet: Montag, 16. Mai 2016 09:52
An: unindented/electron-installer-windows <electron-installer-windows@noreply.github.com>
Cc: miso293 <michael.stollenwerk@icloud.com>; Manual <manual@noreply.github.com>
Betreff: Re: [unindented/electron-installer-windows] Example Fail (#27)

 

The error message seems pretty clear: one of your paths is too long. Can you paste the full path to your app?

In any case, my suggestions would be:

1.	Move your app to a shorter path, e.g. C:\Users\micha\app.
2.	Use Node 5 or 6, as those versions use npm 3, which flattens your dependency folder, resulting in shorter paths.
