### ISSUE TITLE
Electron Installer Windows (Desktop Shortcut)

### ISSUE THREAD

**Issue by miso293** [unindented/electron-installer-windows#28]
Hi,

now with the Node 6 Version the example of „Electron Installer Windows“ works great.

But I have a Question after I run the Installer the Name of the Desktop Shortcut is “Electron” on
Windows 10. 

Why is the name of the Desktop Shortcut not “Poopie” ? And how can I change this ?

Thank you very much.

Michael

**Comment by unindented** [comment]
This is the line that creates the desktop shortcut: https://github.com/unindented/electron-installer-windows/blob/cd3ff22d5036ce9086e1f017e38ae7631a531988/example/src/main/squirrel.js#L55

It should be using the package name. Please look into it and let me know what you find out.

**Comment by miso293** [comment]
What do you mean with package name?

 

This is my package.json

 

{

  "name": "poopie",

  "description": "An example app, built with Electron.",

  "version": "0.0.1",

  "license": "MIT",

  "author": {

    "name": "Daniel Perez Alvarez",

    "email": "unindented@gmail.com",

    "url": "http://unindented.org/"

  },

  "private": true,

  "main": "src/index.js",

  "scripts": {

    "clean": "rimraf dist",

    "start": "electron .",

    "exe32": "electron-packager . poopie --platform win32 --arch ia32 --out dist/ --ignore \"(dist|node_modules/electron.*)\" --icon resources/Icon.ico",

    "exe64": "electron-packager . poopie --platform win32 --arch x64 --out dist/ --ignore \"(dist|node_modules/electron.*)\" --icon resources/Icon.ico",

    "set32": "electron-installer-windows --src dist/poopie-win32-ia32/ --dest dist/installers/ia32/ --config config.json",

    "set64": "electron-installer-windows --src dist/poopie-win32-x64/ --dest dist/installers/x64/ --config config.json",

    "build": "npm run clean && npm run exe32 && npm run set32 && npm run exe64 && npm run set64"

  },

  "devDependencies": {

    "electron-installer-windows": "*",

    "electron-packager": "*",

    "electron-prebuilt": "*",

    "fs-plus": "*",

    "rimraf": "*",

    "yargs": "*"

  }

}

 

Von: Daniel Perez Alvarez [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. Mai 2016 15:02
An: unindented/electron-installer-windows <electron-installer-windows@noreply.github.com>
Cc: miso293 <michael.stollenwerk@icloud.com>; Author <author@noreply.github.com>
Betreff: Re: [unindented/electron-installer-windows] Electron Installer Windows (Desktop Shortcut) (#28)

 

This is the line that creates the desktop shortcut: https://github.com/unindented/electron-installer-windows/blob/cd3ff22d5036ce9086e1f017e38ae7631a531988/example/src/main/squirrel.js#L55

It should be using the package name. Please look into it and let me know what you find out.

**Comment by miso293** [comment]
If i write manually a Name on the Line: 
   
const desktopShortcutPath = path.join(homeDirectory, 'Desktop', `poopy.lnk`)

The Installer will still create a "Electron.ink" Shortcut :-(

**Comment by unindented** [comment]
Maybe it's a problem with the `Update.exe` file provided by [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows)? https://github.com/unindented/electron-installer-windows/blob/cd3ff22d5036ce9086e1f017e38ae7631a531988/example/src/main/squirrel.js#L10

**Comment by miso293** [comment]
What should i do ? Can you reproduce the Problem on your System ?

**Comment by unindented** [comment]
Yup, it also says `Electron`. I'll try to find some free time and look into it.

However, if you depend on this for real work (not a side project), then I'd recommend you look into moving to a project supported by the official Electron team, like https://github.com/electron-userland/electron-builder.

**Comment by miso293** [comment]
Ok Thank you very much.

 

Please write me if you fix this.

 

Have a nice Week.

 

 

Von: Daniel Perez Alvarez [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. Mai 2016 16:02
An: unindented/electron-installer-windows <electron-installer-windows@noreply.github.com>
Cc: miso293 <michael.stollenwerk@icloud.com>; Author <author@noreply.github.com>
Betreff: Re: [unindented/electron-installer-windows] Electron Installer Windows (Desktop Shortcut) (#28)

 

Yup, it also says Electron. I'll try to find some free time and look into it.

However, if you depend on this for real work (not a side project), then I'd recommend you look into moving to a project supported by the official Electron team, like https://github.com/electron-userland/electron-builder.

**Comment by unindented** [comment]
Looks like you need to modify the `ProductName` entry of the generated `.exe` file, using something like [`node-rcedit`](https://github.com/electron/node-rcedit). When you create a shortcut, Windows will use that field for the name of the shortcut.
