### ISSUE TITLE
Invalid URI error?

### ISSUE THREAD

**Issue by arthurscheeren** [unindented/electron-installer-windows#29]
**What version of `electron-installer-windows` are you using?**
2.0
**What version of `node` and `npm` are you using?**
4.0.0   3.8.6
**What operating system are you using?**
Win 8.1
**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
yes
**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
Tried to create the installer.  
electron-installer-windows --src release/win32-x64/app-win32-x64 --dest dist/installers/ --options.version 0.1

**What did you expect to happen?**
create the installer

**What actually happened?**
Creating package (this may take a while)
[Error: Error creating package: Error executing file (1):

 ``` 

electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\\AppData\Local\Temp\electron-116418-7308-13rc54g\app_0.1\nuget\xcheque-dev-tools.nuspec -BasePath C:\Users\user\AppData\Local\Temp\electron-116418-7308-13rc54g\app_0.1\app -OutputDirectory C:\Users\scheeren\AppData\Local\Temp\electron-116418-7308-13rc54g\xcheque-dev-tools_0.1\nuget -NoDefaultExcludes
Invalid URI: The format of the URI could not be determined.
] 'Error: Error creating package: Error executing file (1):   \\nuget -NoDefaultExcludes\nInvalid URI: The format of the URI could not be determined.\r\n\n    at D:\\Projects\\app\\node_modules\\electron-installer-windows\\src\\installer.js:273:21\n    at ChildProcess.<anonymous> (D:\\Projects\\app\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:92:20)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:817:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)'

```

**Comment by unindented** [comment]
Can you post your configuration?

**Comment by JoeKuhns** [comment]
Same error thrown for me.  Here is the complete error I get.

`[Error: Error creating package: Error executing file (1): 
mono /usr/local/lib/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /tmp/electron-11652-41770-spne7w/laerdal-catalog_1.0.0/nuget/laerdal-catalog.nuspec -BasePath /tmp/electron-11652-41770-spne7w/laerdal-catalog_1.0.0/laerdal-catalog -OutputDirectory /tmp/electron-11652-41770-spne7w/laerdal-catalog_1.0.0/nuget -NoDefaultExcludes
Invalid URI: The format of the URI could not be determined.
] 'Error: Error creating package: Error executing file (1): \nmono /usr/local/lib/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /tmp/electron-11652-41770-spne7w/laerdal-catalog_1.0.0/nuget/laerdal-catalog.nuspec -BasePath /tmp/electron-11652-41770-spne7w/laerdal-catalog_1.0.0/laerdal-catalog -OutputDirectory /tmp/electron-11652-41770-spne7w/laerdal-catalog_1.0.0/nuget -NoDefaultExcludes\nInvalid URI: The format of the URI could not be determined.\n\n    at /usr/local/lib/node_modules/electron-installer-windows/src/installer.js:273:21\n    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-installer-windows/src/installer.js:62:5)\n    at emitTwo (events.js:92:20)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:817:16)\n    at Socket.<anonymous> (internal/child_process.js:319:11)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Pipe._onclose (net.js:469:12)'`

**Comment by ahallicks** [comment]
I got this error by accidentally setting:
```
"icon": "./assets/images/logo.png"
```

to 

```
"iconUrl": "./assets/images/logo.png"
```

If you're using iconUrl at all it needs to be a valid URI otherwise it will fail.

**Comment by unindented** [comment]
Ah, mystery solved then. They were surely entering an invalid URL in the `iconUrl` field.

Thank you @ahallicks!

**Comment by geek4teck** [comment]
{
  "iconUrl": "./assets/images/logo.png",
  "icon": "./assets/images/logo.png",
  "tags": [
    "Utility"
  ],
  "authors":["Author Name"],
  "description":"Description goes here",
  "productDescription":"ProductDescription goes here"
}

I am still getting the same error... "Invalid URI: The format of the URI could not be determined."

Can anybody help me please?

**Comment by ahallicks** [comment]
@geek4teck to quote my last post:

> If you're using iconUrl at all it needs to be a valid URI otherwise it will fail.

i.e. you need to host the icon somewhere online and refer to the full href of it

**Comment by geek4teck** [comment]
@ahallicks - Thanks for your quick response.

I posted a HTTPS URL, but it's still the same. 

 

{
  "iconUrl": "https://quiz.advisorymandi.com/assets/img/assets/navBG/2.png",
  "tags": [
    "Utility"
  ],
  "authors":["Author Name"],
  "description":"Description goes here",
  "productDescription":"ProductDescription goes here"
}

**Comment by geek4teck** [comment]
Even if i skip iconURL the same thing happens. 

If i do a local resource or I do http or I do https by all means I get this error

**Invalid URI: The format of the URI could not be determined.**

Can you please help me?

**Comment by geek4teck** [comment]
I just got this working now. I am pasting my solution here, might help somebody in future...

`
"clean": "rimraf dist",
"build": "electron-packager . --out=dist --asar --overwrite",
"setup": "electron-installer-windows --src dist/App-win32-x64/ --dest dist/installers/ --config config.json ",
"final": "npm run clean && npm run build && npm run setup"`

All i did is npm run final which does cleanup first, then build and then setup. 

It worked just perfect, so probably I was missing rimraf dist originally
