### ISSUE TITLE
Cannot find module error after installer creation

### ISSUE THREAD

**Issue by ahallicks** [unindented/electron-installer-windows#30]
**What version of `electron-installer-windows` are you using?**
0.2.0

**What version of `node` and `npm` are you using?**
6.1.0 and 3.8.6

**What operating system are you using?**
Windows 10

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
```
{
  "src": "./out/AppName-win32-x64/",
  "dest": "./out/installers/",
  "iconUrl": "https://url/img/icon.ico",
  "icon": "./assets/images/logo.ico",
  "tags": [
    "Tag 1",
    "Tag2",
    "Tag3"
  ]
}
```
The installer is run with:
`electron-installer-windows --src ./out/AppName-win32-x64/ --dest ./out/installers/ --config config.json`

**What did you expect to happen?**
Everything should work the same as when I start the app from the CLI.

**What actually happened?**
When running the .exe I get an error:

![image](https://cloud.githubusercontent.com/assets/717299/15427113/b4100c3a-1e8a-11e6-8bec-83fc49af03aa.png)

I think it's something to do with the [`windows-shortcuts`](https://www.npmjs.com/package/windows-shortcuts) `node_module`, but when I run the app before creating the installer everything works fine. When I try and run the installer it errors saying that the `windows-shortcuts` node_module could not be found.

**Comment by unindented** [comment]
Are you using `electron-packager`? Are you pointing this tool to the result of `electron-packager`, or to your source folder?

From the error message, my best guess is that you are not including your `node_modules` folder in the final app. The path you provide to this tool has to include everything needed to execute the app.

This doesn't look like a problem with `electron-installer-windows`, but with the organization of your code. I'll close for now.

**Comment by ahallicks** [comment]
Sorry, I am using `electron-packager` to create the package. It must be including `node_modules` because I've got a few others, such as `win-mouse` that do work fine (when I don't require `windows-shortcuts`). So I'm not sure that is the issue.

**Comment by unindented** [comment]
@ahallicks Do you know if `windows-shortcuts` is special in any way? Does it have native dependencies that could cause trouble? https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by ahallicks** [comment]
`windows-shortcuts` is not special as far as I know. It works absolutely fine before creating the .exe.

I run `electron-rebuild` on `node_modules` anyway because `win-mouse` is a bit weird so I don't think that's the issue.

**Comment by unindented** [comment]
Can you check if, after installing your app, the `node_modules/windows-shortcuts` module is in the asar file?

**Comment by unindented** [comment]
Basically we need to know the difference between what `electron-packager` outputs, and what ends up installed in the box after running the installer generated by `electron-installer-windows`.

If you forget about the installer part, does the `.exe` file that `electron-packager` generates work?

**Comment by ahallicks** [comment]
Okay, I don't know what has happened but it now works fine! I switched to running via a script instead of command line through `npm run` and everything now works fine. I'll keep doing some testing to make sure.

Annoyingly I don't know what else I changed that might have made a difference. Sorry about that and thanks for your help on this and the awesome script!

**Comment by unindented** [comment]
No worries. Good luck with your project.
