### ISSUE TITLE
Demo doesn't create a window.

### ISSUE THREAD

**Issue by sylvesterlan100** [unindented/electron-installer-windows#31]
**What version of `electron-installer-windows` are you using?**
v0.2.0

**What version of `node` and `npm` are you using?**
v6.1.0

**What operating system are you using?**
Windows 7 home premium

**Can you compile the [example app](https://github.com/unindented/electron-installer-windows/tree/master/example) successfully?**

It compiles

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-windows.git
$ cd electron-installer-windows/example
$ DEBUG='electron-installer-windows' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-windows`.**
I ran the demo (npm install and npm run build), and tried to run poop.exe from the dist folder. (Running the exe before the installer)

**What did you expect to happen?**
A browser window to pop up.

**What actually happened?**
Nothing happened. A process was started despite there being no windows. I had to open task manager to close it.

**Comment by unindented** [comment]
The app is a menu bar app. It doesn't open a browser window until you click on the menu bar icon.

**Comment by sylvesterlan100** [comment]
Ah thanks!
