### ISSUE TITLE
Custom animated gif during install

### ISSUE THREAD

**Issue by ahallicks** [unindented/electron-installer-windows#34]
Is there a way to use a custom animated gif for the installer? It works great if I overwrite the one in my `node_modules/electron-installer-windows` folder but being able to do this programmatically would be great!

**Comment by unindented** [comment]
Forgot to document the option, but `animation` does what you want: https://github.com/unindented/electron-installer-windows/blob/cd3ff22d5036ce9086e1f017e38ae7631a531988/src/installer.js#L124

**Comment by ahallicks** [comment]
You legend! Thanks so much :)
