### ISSUE TITLE
Always getting a nuget error

### ISSUE THREAD

**Issue by nojvek** [unindented/electron-installer-windows#42]
```
electron-installer-windows --src "dist\DevTools-win32-x64" --dest dist

The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has incomplete content. List of possible elements expected: 'authors, description' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'.
```

**Comment by unindented** [comment]
The error seems pretty obvious to me:

> List of possible elements expected: 'authors, description' 

Looks like you need pass the options `author` and `description` to `electron-installer-windows`.

**Comment by nojvek** [comment]
But that's already in package.json. Shoudn't it pick from there?

**Comment by unindented** [comment]
It does. Try building the example app, and comparing it with yours.

**Comment by nagbhushan** [comment]
How to pass 'authors, description' ???? there is no clue.

**Comment by nagbhushan** [comment]
I tried building exe for windows on my macbook. Its really a mess. wasted my hours.

**Comment by unindented** [comment]
@nagbhushan your rudeness is not appreciated. If you want to contribute and improve the project, create a pull request. Otherwise, please get lost.

**Comment by nagbhushan** [comment]
I already did that. Thank you for wasting my time.

**Comment by passabilities** [comment]
I have description entered and its still saying that description is expected.

**Comment by passabilities** [comment]
ahh i see:

```
options.productDescription

Type: String Default: package.productDescription || package.description

Long description of the application, used in the description field of the nuspec file.
```

productDescription points to description
