### ISSUE TITLE
Question about distribution of .exe somewhere in C:\

### ISSUE THREAD

**Issue by SandrineProusteau** [unindented/electron-installer-windows#73]
Hi, I'm new on Electron, and I'm trying to distribute a very basic app only opening a BrowserWindow with devTools on Windows 10.
I have passed some issues concerning URI et metadata, and now I have generated in /dist/ theses files 
* RELEASES
* app-1.0.0.full.nupkg
* app-1.0.0-setup.exe
* app-1.0.0-setup.msi

When I open the .msi, the windows installer opens, then closes, and the only change I found is a "app Installer" in my C:\Program Files (x86). Inside it, I have a app.exe, and if I click on it, a strange "installer" runs and open my app (with 3 processus ???). Close and re-open do some trange thing, sometimes with errors.

When I delete all that and open the .exe, it opens the strange "installer" and my app, and a /app/ appears in my "C:\Users\ME\AppData\Local\" containing "/app-1.0.0", "/packages", and "Update.exe".

I expected that the .msi would ask me for a path to install my, or by default use C:\Program Files (x86), and generate a basic and functional .exe, perhaps with a desktop / windows menu icon... I'm very confused.

Do you know what is missing for me?

**Comment by unindented** [comment]
This package is just using Squirrel.Windows. You can read all about how the generated installers (.exe, .msi) work here: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/readme.md

You just have to make sure your app responds to the necessary Squirrel events described here: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md

`electron-installer-windows` comes with an example app that does some basic handling of those events, in case you want to check out a working example: https://github.com/unindented/electron-installer-windows/blob/master/example/src/main/squirrel.js
